### ISSUE TITLE
Tests? Which framework?

### ISSUE THREAD

**Issue by maxcal** [timbreitkreutz/omniauth-flickr#14]
I'm working on Flickr based hobby project and could spend some time and love on omniauth-flickr. I was thinking that getting some basic test coverage would be a good first step.

@timbreitkreutz  do you have a preference for a testing framework? Is RSpec ok?

**Comment by timbreitkreutz** [comment]
Sure!  That would be great.  I wanted to do that for a long time but haven't managed to get to it.  Maybe I'll adopt it for the yahoo strategy too :)
