### ISSUE TITLE
Flickr approval requested for every login

### ISSUE THREAD

**Issue by chrissearle** [timbreitkreutz/omniauth-flickr#2]
Gemfile omniauth lines:

gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-flickr'
gem 'omniauth-github'
gem 'omniauth-twitter'

This is running under rails 3.1 - looks like I'm getting omniauth 1.0.1 and omniauth-flickr 0.0.9 from the Gemfile.lock

Facebook, github and twitter all asked for approval for the first login - but subsequently just redirect back to the relevant /auth/*/callback path.

But flickr gives me the http://www.flickr.com/services/oauth/authorize?perms=read&oauth_token=..... authorization approval for each and every login attempt.

If I then approve then the /auth/flickr/callback url is called - it all works from that point on - but there's this manual approve step for every login.

Can't see anything wrong in what this gem is doing - and have seen enough of flickr to at least not throw out the idea that the issue is on their end - but thought I'd raise it here too :)

**Comment by timbreitkreutz** [comment]
Closing ticket as stale--@chrissearle if you are still having this problem please let me know.
